version: "3"

services:
  app:
    build: .
    container_name: properties-typescript-app
    volumes:
      - ./node:/home/node/app
    ports:
      - 3000:3000

  react:
    build: .
    container_name: properties-typescript-react
    volumes:
      - ./react:/home/node/app
    ports:
      - 5173:5173

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306